//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string ADMINISTRATOR_USER {
            get {
                return ResourceManager.GetString("ADMINISTRATOR_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string AUTHORIZATION {
            get {
                return ResourceManager.GetString("AUTHORIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забанить.
        /// </summary>
        public static string BAN {
            get {
                return ResourceManager.GetString("BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировать на срок(в минутах).
        /// </summary>
        public static string BLOCK_FOR_MINUTES {
            get {
                return ResourceManager.GetString("BLOCK_FOR_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировать пользователя №.
        /// </summary>
        public static string BLOCK_USER_N {
            get {
                return ResourceManager.GetString("BLOCK_USER_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокарованная.
        /// </summary>
        public static string BLOCKED_ARTICLE {
            get {
                return ResourceManager.GetString("BLOCKED_ARTICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокированные записи.
        /// </summary>
        public static string BLOCKED_ARTICLES {
            get {
                return ResourceManager.GetString("BLOCKED_ARTICLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить статус статьи.
        /// </summary>
        public static string CHANGE_ARTICLE_STATUS {
            get {
                return ResourceManager.GetString("CHANGE_ARTICLE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить статус.
        /// </summary>
        public static string CHANGE_STATUS {
            get {
                return ResourceManager.GetString("CHANGE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить статус на:.
        /// </summary>
        public static string CHANGE_STATUS_ON {
            get {
                return ResourceManager.GetString("CHANGE_STATUS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить статус пользователя.
        /// </summary>
        public static string CHANGE_USER_STATUS {
            get {
                return ResourceManager.GetString("CHANGE_USER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментировать.
        /// </summary>
        public static string COMMENTING {
            get {
                return ResourceManager.GetString("COMMENTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии.
        /// </summary>
        public static string COMMENTS {
            get {
                return ResourceManager.GetString("COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии к данной статье отключены!.
        /// </summary>
        public static string COMMENTS_DISABLE {
            get {
                return ResourceManager.GetString("COMMENTS_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете оставлять комментарии!.
        /// </summary>
        public static string COMMENTS_DISABLE_FOR_YOU {
            get {
                return ResourceManager.GetString("COMMENTS_DISABLE_FOR_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать пост.
        /// </summary>
        public static string CREATE_ARTICLE {
            get {
                return ResourceManager.GetString("CREATE_ARTICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По Умолчанию.
        /// </summary>
        public static string DEFAULT {
            get {
                return ResourceManager.GetString("DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лента.
        /// </summary>
        public static string FEED {
            get {
                return ResourceManager.GetString("FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте.
        /// </summary>
        public static string HELLO {
            get {
                return ResourceManager.GetString("HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модератор.
        /// </summary>
        public static string MODERATOR_USER {
            get {
                return ResourceManager.GetString("MODERATOR_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Никнейм.
        /// </summary>
        public static string NICKNAME {
            get {
                return ResourceManager.GetString("NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок.
        /// </summary>
        public static string PERIOD {
            get {
                return ResourceManager.GetString("PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перманентно.
        /// </summary>
        public static string PERMANENT {
            get {
                return ResourceManager.GetString("PERMANENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посты.
        /// </summary>
        public static string POSTS {
            get {
                return ResourceManager.GetString("POSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только для чтения.
        /// </summary>
        public static string READONLY {
            get {
                return ResourceManager.GetString("READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина.
        /// </summary>
        public static string REASON {
            get {
                return ResourceManager.GetString("REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация нового пользователя.
        /// </summary>
        public static string REG_NEW_USER {
            get {
                return ResourceManager.GetString("REG_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string REGISTRATION {
            get {
                return ResourceManager.GetString("REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить вход.
        /// </summary>
        public static string SIGN_IN {
            get {
                return ResourceManager.GetString("SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теги.
        /// </summary>
        public static string TAGS {
            get {
                return ResourceManager.GetString("TAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разбанить.
        /// </summary>
        public static string UNBAN {
            get {
                return ResourceManager.GetString("UNBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До:.
        /// </summary>
        public static string UNTIL {
            get {
                return ResourceManager.GetString("UNTIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Был заблокирован:.
        /// </summary>
        public static string WAS_BANNED {
            get {
                return ResourceManager.GetString("WAS_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напишите теги через запятую.
        /// </summary>
        public static string WRITE_TAGS_WITH_COMMAS {
            get {
                return ResourceManager.GetString("WRITE_TAGS_WITH_COMMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль.
        /// </summary>
        public static string WRONG_LOGIN_OR_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_LOGIN_OR_PASSWORD", resourceCulture);
            }
        }
    }
}
